data:
  batch_size: 64
  shuffle: True
  num_workers: 2
  context_len: 256
training:
  num_epochs: 50
  lr: 0.0005
  weight_decay:  0.0005
  min_lr: 0.00005
model:
  model_dir: "saved_models/classifier"
  name: "GPT2"
freezer:
  transformer: 0.
  embeddings: false
  pos: false
  lm_head: false
  ln_f: false
seed: 42