data:
  batch_size: 16
  shuffle: True
  num_workers: 2
  context_len: 256
  labelintext: True
training:
  num_epochs: 1
  lr: 0.00005
  weight_decay:  0.0
  min_lr: 0.00005
model:
  model_dir: "saved_models/Llama3.2-1B"
  name: "Llama"
freezer:
  transformer: 4.
  embeddings: True
  pos: True
  lm_head: True
  ln_f: True
seed: 42